### PR TITLE
Update readme.md to fix broken documentation links

### PR DESCRIPTION
**Pull request by csteegz**
Fix broken documentation links

### CODE REVIEW

**Comment by csteegz** [comment]
FWIW @lmolkova  it looks like something's up with the VSTS build triggers.

**Comment by lmolkova** [comment]
@tokapan do you know if we have VSTS builds enabled for the forks?

@csteegz thanks a log for your contribution! I'll go ahead and merge it, as there is nothing to break the build in this change.

**Comment by lmolkova** [comment]
@tokaplan an do you know if we have VSTS builds enabled for the forks?

**Comment by tokaplan** [comment]
No idea how that would work, but I know SDK team has builds enabled for forks off SDK branches, so maybe ask Dmitry or Cijo. I haven’t done anything in that direction.

**Pull request merged**
